apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: n8n-secret-key-generator
spec:
  length: 256
  symbols: 0
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: n8n-password-generator
spec:
  length: 64
  symbols: 0
  allowRepeat: true
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: n8n-cluster
  namespace: n8n
spec:
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: n8n-password-generator
  template:
    data:
      username: n8n
      password: "{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: n8n/postgres
          property: password
    - match:
        secretKey: username
        remoteRef:
          remoteKey: n8n/postgres
          property: username
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-postgres
  namespace: n8n
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: n8n-cluster-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - extract:
        key: n8n/postgres
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  updatePolicy: IfNotExists
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: n8n-secret-key-generator
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: n8n/server
          property: encryption_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-backup-s3-account
  namespace: n8n
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: n8n-backup-s3-account
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACCESS_KEY: "{{ .access_key }}"
        SECRET_KEY: "{{ .secret_key }}"
  dataFrom:
    - extract:
        key: n8n/s3
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secret-env
  namespace: vault
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: n8n-secret-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_TYPE: postgresdb
        DB_POSTGRESDB_HOST: n8n-cluster-rw
        DB_POSTGRESDB_PORT: "5432"
        DB_POSTGRESDB_DATABASE: n8n
        DB_POSTGRESDB_USER: "{{ .username }}"
        DB_POSTGRESDB_PASSWORD: "{{ .password }}"
        N8N_ENCRYPTION_KEY: "{{ .encryption_key }}"

        N8N_SMTP_HOST: smtp.gmail.com
        N8N_SMTP_PORT: "587"
        N8N_SMTP_USER: "{{ .smtp_username }}"
        N8N_SMTP_PASS: "{{ .smtp_password }}"
        N8N_SMTP_SENDER: no-reply@${EXTERNAL_DOMAIN}
        N8N_SMTP_SSL: "false"
        N8N_SMTP_STARTTLS: "true"
  dataFrom:
    - extract:
        key: n8n/postgres
    - extract:
        key: n8n/server
  data:
    - secretKey: smtp_username
      remoteRef:
        key: n8n/smtp
        property: username
    - secretKey: smtp_password
      remoteRef:
        key: n8n/smtp
        property: password
