apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisReplication
metadata:
  name: paperless-redis
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis:v8.4.2
    imagePullPolicy: IfNotPresent
    redisSecret:
      name: paperless-redis-credentials
      key: password
    resources:
      requests:
        cpu: 10m
        memory: 20Mi
      limits:
        memory: 20Mi
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: local-path
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:v1.81.0
    resources:
      requests:
        cpu: 10m
        memory: 24Mi
      limits:
        memory: 24Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - paperless-redis
          topologyKey: "kubernetes.io/hostname"
---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisSentinel
metadata:
  name: paperless-redis
spec:
  clusterSize: 3
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
  redisSentinelConfig:
    masterGroupName: mymaster
    redisReplicationName: paperless-redis
    redisReplicationPassword:
      secretKeyRef:
        name: paperless-redis-credentials
        key: password
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:v1.81.0
    resources:
      requests:
        cpu: 10m
        memory: 20Mi
      limits:
        memory: 20Mi
  kubernetesConfig:
    image: quay.io/opstree/redis-sentinel:v8.4.2
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 10m
        memory: 15Mi
      limits:
        memory: 15Mi
