apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: paperless-secret-key-generator
spec:
  length: 256
  symbols: 0
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: paperless-password-generator
spec:
  length: 64
  symbols: 0
  allowRepeat: true
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: paperless-cluster
  namespace: paperless
spec:
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: paperless-password-generator
  template:
    data:
      username: paperless
      password: "{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: paperless/postgres
          property: password
    - match:
        secretKey: username
        remoteRef:
          remoteKey: paperless/postgres
          property: username
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-postgres
  namespace: paperless
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: paperless-cluster-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - extract:
        key: paperless/postgres
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: paperless-redis
  namespace: paperless
spec:
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: paperless-password-generator
  template:
    data:
      password: "{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: paperless/redis
          property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-redis
  namespace: paperless
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: paperless-redis-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: paperless/redis
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: paperless-admin-user
  namespace: paperless
spec:
  updatePolicy: IfNotExists
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: paperless-password-generator
  template:
    data:
      username: root
      password: "{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: paperless/admin
          property: password
    - match:
        secretKey: username
        remoteRef:
          remoteKey: paperless/admin
          property: username
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: paperless-secret-key
  namespace: paperless
spec:
  updatePolicy: IfNotExists
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: paperless-secret-key-generator
  template:
    data:
      secret_key: "{{ .password }}"
  data:
    - match:
        secretKey: secret_key
        remoteRef:
          remoteKey: paperless/server
          property: secret_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-backup-s3-account
  namespace: paperless
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: paperless-backup-s3-account
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACCESS_KEY: "{{ .access_key }}"
        SECRET_KEY: "{{ .secret_key }}"
  dataFrom:
    - extract:
        key: paperless/s3
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secret-env
  namespace: vault
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: paperless-secret-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PAPERLESS_ADMIN_USER: "{{ .admin_username }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .admin_password }}"
        PAPERLESS_SECRET_KEY: "{{ .secret_key }}"
        PAPERLESS_REDIS: |-
          redis://:{{ .redis_password }}@paperless-redis-master:6379
        # Database
        PAPERLESS_DBHOST: paperless-cluster-rw
        PAPERLESS_DBPORT: "5432"
        PAPERLESS_DBNAME: paperless
        PAPERLESS_DBUSER: "{{ .username }}"
        PAPERLESS_DBPASS: "{{ .password }}"
        PAPERLESS_EMAIL_HOST: smtp.gmail.com
        PAPERLESS_EMAIL_PORT: "587"
        PAPERLESS_EMAIL_USE_TLS: "true"
        PAPERLESS_EMAIL_HOST_USER: "{{ .smtp_username }}"
        PAPERLESS_EMAIL_HOST_PASSWORD: "{{ .smtp_password }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
          {
            "openid_connect": {
              "OAUTH_PKCE_ENABLED": true,
              "APPS": [
                {
                  "provider_id": "authentik",
                  "name": "authentik",
                  "client_id": "{{.client_id}}",
                  "secret": "{{.client_secret}}",
                  "settings": {
                    "server_url": "https://authentik.${EXTERNAL_DOMAIN}/application/o/paperless/.well-known/openid-configuration",
                    "fetch_userinfo": true
                  }
                }
              ],
              "SCOPE": ["openid", "profile", "email"]
            }
          }
  dataFrom:
    - extract:
        key: paperless/postgres
    - extract:
        key: paperless/server
    - extract:
        key: paperless/authentik
  data:
    - secretKey: redis_password
      remoteRef:
        key: paperless/redis
        property: password
    - secretKey: admin_username
      remoteRef:
        key: paperless/admin
        property: username
    - secretKey: admin_password
      remoteRef:
        key: paperless/admin
        property: password
    - secretKey: smtp_username
      remoteRef:
        key: paperless/smtp
        property: username
    - secretKey: smtp_password
      remoteRef:
        key: paperless/smtp
        property: password
