apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik

labels:
  - pairs:
      app.kubernetes.io/module: authentik

resources:
  - namespace.yaml
  - store.yaml
  - pgcluster.yaml
  - network.yaml
  - secrets.yaml
  - helm.yaml
  - old-ingress.yaml
