apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: authentik-secret-key-generator
spec:
  length: 256
  symbols: 0
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: authentik-password-generator
spec:
  length: 64
  symbols: 0
  allowRepeat: true
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: authentik-cluster
  namespace: authentik
spec:
  # TODO: change to Replace after restore
  updatePolicy: IfNotExists
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: authentik-password-generator
  template:
    data:
      username: authentik
      password: "{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: authentik/postgres
          property: password
    - match:
        secretKey: username
        remoteRef:
          remoteKey: authentik/postgres
          property: username
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: authentik-secret-env
  namespace: authentik
spec:
  updatePolicy: IfNotExists
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: authentik-secret-key-generator
  template:
    data:
      secret_key: "{{ .password }}"
  data:
    - match:
        secretKey: secret_key
        remoteRef:
          remoteKey: authentik/server
          property: secret_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret-env
  namespace: authentik
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-secret-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SECRET_KEY: "{{ .secret_key }}"
        DB_USERNAME: "{{ .dbuser }}"
        DB_PASSWORD: "{{ .dbpass }}"
        SMTP_USERNAME: "{{ .smtp_username }}"
        SMTP_PASSWORD: "{{ .smtp_password }}"

  dataFrom:
    - extract:
        key: authentik/server
  data:
    - secretKey: dbuser
      remoteRef:
        key: authentik/postgres
        property: username
    - secretKey: dbpass
      remoteRef:
        key: authentik/postgres
        property: password
    - secretKey: smtp_username
      remoteRef:
        key: authentik/smtp
        property: username
    - secretKey: smtp_password
      remoteRef:
        key: authentik/smtp
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-postgres
  namespace: authentik
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-cluster-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - extract:
        key: authentik/postgres
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-minio-svc-account
  namespace: authentik
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-backup-s3-account
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACCESS_KEY: "{{ .access_key }}"
        SECRET_KEY: "{{ .secret_key }}"
  dataFrom:
    - extract:
        key: authentik/s3
