apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: &app searxng

labels:
  - pairs:
      app.kubernetes.io/module: *app

configMapGenerator:
  - name: searxng-settings
    namespace: *app
    options:
      disableNameSuffixHash: true
    files:
      - resources/settings.yml
      - resources/limiter.toml

resources:
  - namespace.yaml
  - secrets.yaml
  - helm.yaml
  - redis.yaml
