apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: searxng-token-generator
spec:
  length: 256
  symbols: 0
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: searxng-password-generator
spec:
  length: 64
  symbols: 0
  allowRepeat: true
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: searxng-redis
  namespace: searxng
spec:
  updatePolicy: IfNotExists
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: searxng-password-generator
  template:
    data:
      password: "{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: searxng/redis
          property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-redis
  namespace: searxng
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: searxng-redis-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: searxng/redis
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: searxng-secret-key
  namespace: searxng
spec:
  updatePolicy: IfNotExists
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: searxng-token-generator
  template:
    data:
      token: "{{ .password }}"
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: searxng/server
          property: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-secret-env
  namespace: vault
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: searxng-secret-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SEARXNG_SECRET: "{{ .token }}"
        SEARXNG_VALKEY_URL: "valkey://:{{.password}}@searxng-redis-master:6379/0"
  dataFrom:
    - extract:
        key: searxng/server
    - extract:
        key: searxng/redis
