apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: netbox-bucket
  namespace: netbox
spec:
  generateBucketName: netbox
  storageClassName: ceph-bucket
  additionalConfig:
    maxSize: 5G
