apiVersion: generators.external-secrets.io/v1alpha1
kind: UUID
metadata:
  name: netbox-uuid-generator
spec: {}
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: netbox-token-generator
spec:
  length: 256
  symbols: 0
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: netbox-password-generator
spec:
  length: 64
  symbols: 0
  allowRepeat: true
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: netbox-cluster
  namespace: netbox
spec:
  updatePolicy: IfNotExists
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: netbox-password-generator
  template:
    data:
      username: netbox
      password: "{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: netbox/postgres
          property: password
    - match:
        secretKey: username
        remoteRef:
          remoteKey: netbox/postgres
          property: username
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-postgres
  namespace: netbox
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: netbox-cluster-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - extract:
        key: netbox/postgres
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: netbox-redis
  namespace: netbox
spec:
  updatePolicy: IfNotExists
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: netbox-password-generator
  template:
    data:
      password: "{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: netbox/redis
          property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-redis
  namespace: netbox
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: netbox-redis-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: netbox/redis
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: netbox-secret-key
  namespace: netbox
spec:
  updatePolicy: IfNotExists
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: netbox-token-generator
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: netbox/server
          property: secret_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-superuser
  namespace: netbox
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: netbox-superuser
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: admin
        email: no-reply@${EXTERNAL_DOMAIN}
        api_token: "{{ .uuid }}"
        password: "{{ .password }}"

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: netbox-password-generator
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: UUID
          name: netbox-uuid-generator
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: netbox-superuser
  namespace: netbox
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    secret:
      name: netbox-superuser
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: netbox/admin
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: netbox/admin
          property: password
    - match:
        secretKey: api_token
        remoteRef:
          remoteKey: netbox/admin
          property: api_token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-server
  namespace: netbox
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: netbox-server
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: netbox/server
    - extract:
        key: netbox/admin
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-operator
  namespace: netbox
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: netbox-operator
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: netbox/operator
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-backup-s3-account
  namespace: netbox
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: netbox-backup-s3-account
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACCESS_KEY: "{{ .access_key }}"
        SECRET_KEY: "{{ .secret_key }}"
  dataFrom:
    - extract:
        key: netbox/s3
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-smtp
  namespace: netbox
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: netbox-smtp
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: netbox/smtp
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-oidc
  namespace: netbox
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: netbox-oidc
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: netbox/authentik
