apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: redis-operator
  namespace: redis-operator
spec:
  interval: 24h
  url: https://ot-container-kit.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: redis-operator
spec:
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: redis-operator
      version: 0.*
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: redis-operator
  values:
    replicas: 2
