apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: docker.io
endpoints:
  - url: https://harbor.${}/v2/docker.io
    overridePath: true
skipFallback: false
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: ghcr.io
endpoints:
  - url: https://harbor.${}/v2/ghcr.io
    overridePath: true
skipFallback: false
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: registry.k8s.io
endpoints:
  - url: https://harbor.${}/v2/registry.k8s.io
    overridePath: true
skipFallback: false
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: quay.io
endpoints:
  - url: https://harbor.${}/v2/quay.io
    overridePath: true
skipFallback: false
