apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vault
  namespace: vault
spec:
  interval: 24h
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: vault
      version: 0.32.x
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: vault
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    global:
      tlsDisable: false

    server:
      volumeMounts:
        - name: vault-internal-tls
          mountPath: /var/run/config/vault-internal-tls
        - name: cluster-bundle-ca
          mountPath: /var/run/config/cluster-bundle-ca
      volumes:
        - name: vault-internal-tls
          secret:
            defaultMode: 420
            secretName: vault-internal-tls
        - name: cluster-bundle-ca
          configMap:
            name: cluster-bundle-ca
            defaultMode: 420
      extraEnvironmentVars:
        VAULT_CACERT: /var/run/config/cluster-bundle-ca/ca-bundle.crt
      ha:
        enabled: true
        raft:
          enabled: true
          setNodeId: true
          config: |
            ui = true
            cluster_name = "vault-cluster"

            listener "tcp" {
              address = "[::]:8200"
              cluster_address = "[::]:8201"
              # Enable unauthenticated metrics access (necessary for Prometheus Operator)
              tls_cert_file = "/var/run/config/vault-internal-tls/tls.crt"
              tls_key_file = "/var/run/config/vault-internal-tls/tls.key"
              tls_client_ca_file = "/var/run/config/vault-internal-tls/ca.crt"
              telemetry {
                unauthenticated_metrics_access = "true"
              }
            }

            storage "raft" {
              path = "/vault/data"
              retry_join {
                leader_api_addr = "https://vault-0.vault-internal:8200"
                leader_ca_cert_file = "/var/run/config/vault-internal-tls/ca.crt"
                leader_client_cert_file = "/var/run/config/vault-internal-tls/tls.crt"
                leader_client_key_file = "/var/run/config/vault-internal-tls/tls.key"
              }
              retry_join {
                leader_api_addr = "https://vault-1.vault-internal:8200"
                leader_ca_cert_file = "/var/run/config/vault-internal-tls/ca.crt"
                leader_client_cert_file = "/var/run/config/vault-internal-tls/tls.crt"
                leader_client_key_file = "/var/run/config/vault-internal-tls/tls.key"
              }
              retry_join {
                leader_api_addr = "https://vault-2.vault-internal:8200"
                leader_ca_cert_file = "/var/run/config/vault-internal-tls/ca.crt"
                leader_client_cert_file = "/var/run/config/vault-internal-tls/tls.crt"
                leader_client_key_file = "/var/run/config/vault-internal-tls/tls.key"
              }
            }

            service_registration "kubernetes" {}
      ui:
        enabled: true
      ingress:
        enabled: false
      dataStorage:
        size: 2Gi
        storageClass: local-path
    injector:
      enabled: false
