apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

labels:
  - pairs:
      app.kubernetes.io/module: vault

configMapGenerator:
  - name: vault-backup-scripts
    options:
      labels:
        kustomize.toolkit.fluxcd.io/substitute: disabled
    files:
      - scripts/backup.sh

resources:
  - namespace.yaml
  - secrets.yaml
  - cronjob.yaml
  - certificates.yaml
  - ingress.yaml
  - helm.yaml
