apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-backup-credentials
  namespace: vault
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vault-backup-s3-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        credentials: |
          [default]
          aws_access_key_id = {{ .access_key }}
          aws_secret_access_key = {{ .secret_key }}
        config: |
          [default]
          skip_verify = false
  dataFrom:
    - extract:
        key: vault/s3
