apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: cluster-bundle-ca
spec:
  sources:
    - useDefaultCAs: true

    - secret:
        name: home-ca
        key: home-root.crt

    - secret:
        name: cluster-intermediate-ca
        key: tls.crt

  target:
    configMap:
      key: ca-bundle.crt
      metadata:
        labels:
          app.kubernetes.io/generated-by: trust-manager
    secret:
      key: ca-bundle.crt
      metadata:
        labels:
          app.kubernetes.io/generated-by: trust-manager
