apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

secretGenerator:
  - name: home-ca
    type: Opaque
    namespace: cert-manager
    options:
      disableNameSuffixHash: true
    files:
      - home-root.crt

resources:
  - bundle.yaml
