apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/category: apps
      app.kubernetes.io/environment: production

resources:
  - authentik
  - external-dns
  - harbor
  - immich
  - joplin
  - n8n
  - netbox
  - openwebui
  - pangolin
  - paperless
  # - portainer
  - searxng
  - termix
  - uptime
  - vault
  - vaultwarden
