apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: &app termix

labels:
  - pairs:
      app.kubernetes.io/module: *app

resources:
  - namespace.yaml
  - helm.yaml
  - network.yaml
