apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: openwebui-token-generator
spec:
  length: 256
  symbols: 0
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: openwebui-password-generator
spec:
  length: 64
  symbols: 0
  allowRepeat: true
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: openwebui-cluster
  namespace: openwebui
spec:
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: openwebui-password-generator
  template:
    data:
      username: openwebui
      password: "{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: openwebui/postgres
          property: password
    - match:
        secretKey: username
        remoteRef:
          remoteKey: openwebui/postgres
          property: username
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-postgres
  namespace: openwebui
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: openwebui-cluster-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - extract:
        key: openwebui/postgres
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-backup-s3-account
  namespace: openwebui
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: openwebui-backup-s3-account
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACCESS_KEY: "{{ .access_key }}"
        SECRET_KEY: "{{ .secret_key }}"
  dataFrom:
    - extract:
        key: openwebui/s3
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: openwebui-redis
  namespace: openwebui
spec:
  updatePolicy: IfNotExists
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: openwebui-password-generator
  template:
    data:
      password: "{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: openwebui/redis
          property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-redis
  namespace: openwebui
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: openwebui-redis-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: openwebui/redis
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: openwebui-secret-key
  namespace: openwebui
spec:
  updatePolicy: IfNotExists
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: openwebui-token-generator
  template:
    data:
      token: "{{ .password }}"
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: openwebui/server
          property: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-secret-env
  namespace: vault
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: openwebui-secret-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: postgresql://{{ .pg_username }}:{{ .pg_password }}@openwebui-cluster-rw:5432/openwebui
        REDIS_URL: redis://:{{.redis_password}}@mymaster:6379/0
        WEBSOCKET_REDIS_URL: redis://:{{.redis_password}}@mymaster:6379/1
        WEBUI_SECRET_KEY: "{{ .token }}"
        OAUTH_CLIENT_ID: "{{ .client_id }}"
        OAUTH_CLIENT_SECRET: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: openwebui/authentik
    - extract:
        key: openwebui/server
  data:
    - secretKey: pg_username
      remoteRef:
        key: openwebui/postgres
        property: username
    - secretKey: pg_password
      remoteRef:
        key: openwebui/postgres
        property: password
    - secretKey: redis_password
      remoteRef:
        key: openwebui/redis
        property: password
