apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: &app uptime

labels:
  - pairs:
      app.kubernetes.io/module: *app

configMapGenerator:
  - name: uptime-backup-scripts
    namespace: *app
    options:
      disableNameSuffixHash: true
    files:
      - scripts/backup.sh

resources:
  - namespace.yaml
  - helm.yaml
  - network.yaml
  - secrets.yaml
  - cronjob.yaml
