apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/subcategory: security

resources:
  - cert-manager.yaml
  - trust-manager.yaml
  - eso.yaml
