apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: harbor-bucket
  namespace: harbor
spec:
  bucketName: harbor
  storageClassName: ceph-bucket
  additionalConfig:
    maxSize: 100G
