apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harbor

labels:
  - pairs:
      app.kubernetes.io/module: harbor

configMapGenerator:
  - name: harbor-dashboards
    options:
      disableNameSuffixHash: true
      labels:
        grafana/dashboard: "true"
      annotations:
        grafana/folder: Harbor
    files:
      - dashboard.json

resources:
  - namespace.yaml
  - certificates.yaml
  - bucket.yaml
  - secrets.yaml
  - store.yaml
  - pgcluster.yaml
  - redis.yaml
  - helm.yaml
