apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: harbor-password-generator
spec:
  length: 64
  symbols: 0
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: harbor-secret-generator
spec:
  length: 16
  symbols: 0
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: harbor-csrf-generator
spec:
  length: 32
  symbols: 0
  allowRepeat: true
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: harbor-cluster
  namespace: harbor
spec:
  updatePolicy: IfNotExists
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: harbor-password-generator
  template:
    data:
      username: harbor
      password: "{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: harbor/postgres
          property: password
    - match:
        secretKey: username
        remoteRef:
          remoteKey: harbor/postgres
          property: username
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: harbor-redis
  namespace: harbor
spec:
  updatePolicy: IfNotExists
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: harbor-password-generator
  template:
    data:
      password: "{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: harbor/redis
          property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-redis
  namespace: harbor
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-redis-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        REDIS_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: harbor/redis
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: harbor-secret-key
  namespace: harbor
spec:
  updatePolicy: IfNotExists
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: harbor-secret-generator
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: harbor/key
          property: secret_key
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: harbor-core-secret
  namespace: harbor
spec:
  updatePolicy: IfNotExists
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: harbor-secret-generator
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: harbor/core
          property: secret
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: harbor-jobservice-secret
  namespace: harbor
spec:
  updatePolicy: IfNotExists
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: harbor-secret-generator
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: harbor/jobservice
          property: secret
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: harbor-registry-secret
  namespace: harbor
spec:
  updatePolicy: IfNotExists
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: harbor-secret-generator
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: harbor/registry
          property: secret
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: harbor-core-csrf
  namespace: harbor
spec:
  updatePolicy: IfNotExists
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: harbor-csrf-generator
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: harbor/core
          property: csrf
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-secret-key
  namespace: harbor
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-secret-key
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secretKey: "{{ .secret_key }}"
  dataFrom:
    - extract:
        key: harbor/key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-core-secret
  namespace: harbor
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-core-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secret: "{{ .secret }}"
  dataFrom:
    - extract:
        key: harbor/core
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-core-csrf
  namespace: harbor
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-core-csrf
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CSRF_KEY: "{{ .csrf }}"
  dataFrom:
    - extract:
        key: harbor/core
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-jobservice-secret
  namespace: harbor
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-jobservice-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secret: "{{ .secret }}"
  dataFrom:
    - extract:
        key: harbor/jobservice
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registry-secret
  namespace: harbor
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-registry-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secret: "{{ .secret }}"
  dataFrom:
    - extract:
        key: harbor/registry
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-postgres
  namespace: harbor
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-cluster-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - extract:
        key: harbor/postgres
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-backup-s3-account
  namespace: harbor
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-backup-s3-account
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACCESS_KEY: "{{ .access_key }}"
        SECRET_KEY: "{{ .secret_key }}"
  dataFrom:
    - extract:
        key: harbor/s3
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: harbor-bucket
  namespace: harbor
spec:
  refreshInterval: 2h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    secret:
      name: harbor-bucket
  template:
    data:
      access_key: "{{ .AWS_ACCESS_KEY_ID }}"
      secret_key: "{{ .AWS_SECRET_ACCESS_KEY }}"
  data:
    - match:
        secretKey: access_key
        remoteRef:
          remoteKey: harbor/storage
          property: access_key
    - match:
        secretKey: secret_key
        remoteRef:
          remoteKey: harbor/storage
          property: secret_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-s3-storage
  namespace: harbor
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-s3-storage
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        REGISTRY_STORAGE_S3_ACCESSKEY: "{{ .access_key }}"
        REGISTRY_STORAGE_S3_SECRETKEY: "{{ .secret_key }}"
  dataFrom:
    - extract:
        key: harbor/storage
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: harbor-admin
  namespace: harbor
spec:
  updatePolicy: IfNotExists
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: harbor-password-generator
  template:
    data:
      username: admin
      password: "{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: harbor/admin
          property: password
    - match:
        secretKey: username
        remoteRef:
          remoteKey: harbor/admin
          property: username
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: harbor-registry-credentials
  namespace: harbor
spec:
  updatePolicy: IfNotExists
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: harbor-password-generator
  template:
    data:
      username: harbor_registry_user
      password: "{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: harbor/registry
          property: password
    - match:
        secretKey: username
        remoteRef:
          remoteKey: harbor/registry
          property: username
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin
  namespace: harbor
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-admin-password
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        HARBOR_ADMIN_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: harbor/admin
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registry-credentials
  namespace: harbor
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-registry-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        REGISTRY_PASSWD: "{{ .password }}"
        REGISTRY_HTPASSWD: '{{ htpasswd .username .password "bcrypt"}}'
  dataFrom:
    - extract:
        key: harbor/registry
