apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ak-outpost-ldap
spec:
  entryPoints:
    - ldaps
  routes:
    - match: HostSNI(`authentik.${INTERNAL_DOMAIN}`)
      services:
        - name: ak-outpost-ldap
          port: 389
  tls:
    secretName: authentik-ingress-tls
    domains:
      - main: authentik.${INTERNAL_DOMAIN}
