apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: redis-operator
  namespace: redis-operator
spec:
  namespaceSelector:
    matchNames:
      - redis-operator
  selector:
    matchLabels:
      name: redis-operator
  podTargetLabels:
    - name
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 10s
