apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: truenas
  namespace: traefik-system
spec:
  serverName: truenas.${INTERNAL_DOMAIN}
  insecureSkipVerify: false
---
apiVersion: v1
kind: Service
metadata:
  name: rustfs
  namespace: traefik-system
  annotations:
    traefik.ingress.kubernetes.io/service.serverstransport: traefik-system-truenas@kubernetescrd
spec:
  ports:
    - name: https-dashboard
      port: 30293
      protocol: TCP
      targetPort: https-dashboard
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: rustfs
  namespace: traefik-system
subsets:
  - addresses:
      - ip: 192.168.30.20
    ports:
      - name: https-dashboard
        port: 30293
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  name: rustfs
  namespace: traefik-system
spec:
  ingressClassName: traefik
  rules:
    - host: &host rustfs.${INTERNAL_DOMAIN}
      http:
        paths:
          - backend:
              service:
                name: rustfs
                port:
                  name: https-dashboard
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - *host
      secretName: rustfs-ingress-tls
