apiVersion: v1
kind: Namespace
metadata:
  name: nfs-subdir
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-subdir
  namespace: nfs-subdir
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir
  namespace: nfs-subdir
spec:
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.*
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir
  values:
    replicaCount: 1
    nfs:
      server: 192.168.30.20
      path: /mnt/main/Cluster/Production/Volumes

    storageClass:
      name: nfs
      pathPattern: "$${.PVC.namespace}/$${.PVC.name}"
      archiveOnDelete: true
