apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portainer

labels:
  - pairs:
      app.kubernetes.io/module: portainer

resources:
  - https://downloads.portainer.io/ce2-33/portainer-agent-k8s-lb.yaml
  - network.yaml

patches:
  - path: service-patch.yaml
  - path: deployment-patch.yaml
