apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: thanos-bucket
  namespace: monitoring
spec:
  bucketName: thanos
  storageClassName: ceph-bucket
  additionalConfig:
    maxSize: 100G
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki-bucket
  namespace: monitoring
spec:
  generateBucketName: loki
  storageClassName: ceph-bucket
  additionalConfig:
    maxSize: 50G
