apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - buckets.yaml
  - secrets.yaml
  - prometheus.yaml
  - thanos.yaml
  - loki.yaml
  - alloy.yaml
  - grafana.yaml
  - krr.yaml

configMapGenerator:
  - name: alloy
    namespace: monitoring
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/component: config
    files:
      - config.alloy
