apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: &app vaultwarden

labels:
  - pairs:
      app.kubernetes.io/module: *app

resources:
  - namespace.yaml
  - secrets.yaml
  - store.yaml
  - pgcluster.yaml
  - helm.yaml
  - network.yaml
