apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-cluster
  namespace: vaultwarden
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6-standard-trixie
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: local-path
    size: 2Gi

  bootstrap:
    initdb:
      database: vaultwarden
      owner: vaultwarden
      secret:
        name: vaultwarden-cluster-credentials

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: backup-store

  monitoring:
    enablePodMonitor: true
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: vaultwarden-cluster-backup
  namespace: vaultwarden
spec:
  cluster:
    name: vaultwarden-cluster
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
