apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: vaultwarden-admin-token-generator
spec:
  length: 256
  symbols: 0
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: vaultwarden-password-generator
spec:
  length: 64
  symbols: 0
  allowRepeat: true
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: vaultwarden-cluster
  namespace: vaultwarden
spec:
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: vaultwarden-password-generator
  template:
    data:
      username: vaultwarden
      password: "{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: vaultwarden/postgres
          property: password
    - match:
        secretKey: username
        remoteRef:
          remoteKey: vaultwarden/postgres
          property: username
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  updatePolicy: IfNotExists
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: vaultwarden-admin-token-generator
  template:
    data:
      admin_token: "{{ .password }}"
  data:
    - match:
        secretKey: admin_token
        remoteRef:
          remoteKey: vaultwarden/server
          property: admin_token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vaultwarden-admin-token
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        TOKEN: "{{ .admin_token_hash }}"

  dataFrom:
    - extract:
        key: vaultwarden/server
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-postgres
  namespace: vaultwarden
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vaultwarden-cluster-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - extract:
        key: vaultwarden/postgres
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-backup-s3-account
  namespace: vaultwarden
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vaultwarden-backup-s3-account
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACCESS_KEY: "{{ .access_key }}"
        SECRET_KEY: "{{ .secret_key }}"
  dataFrom:
    - extract:
        key: vaultwarden/s3
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-backup-s3-credentials
  namespace: vault
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vaultwarden-backup-s3-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        credentials: |
          [default]
          aws_access_key_id = {{ .access_key }}
          aws_secret_access_key = {{ .secret_key }}
        config: |
          [default]
          skip_verify = false
  dataFrom:
    - extract:
        key: vaultwarden/s3
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-secret-env
  namespace: vault
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vaultwarden-secret-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: postgresql://{{ .pg_username }}:{{ .pg_password }}@vaultwarden-cluster-rw:5432/vaultwarden
        SMTP_USERNAME: "{{ .username }}"
        SMTP_PASSWORD: "{{ .password }}"
        SSO_CLIENT_ID: "{{ .client_id }}"
        SSO_CLIENT_SECRET: "{{ .client_secret }}"
        ADMIN_TOKEN: "{{ .admin_token_hash }}"
        YUBICO_CLIENT_ID: "{{ .yubico_client_id }}"
        YUBICO_SECRET_KEY: "{{ .yubico_secret_key }}"
  dataFrom:
    - extract:
        key: vaultwarden/smtp
    - extract:
        key: vaultwarden/authentik
    - extract:
        key: vaultwarden/server
  data:
    - secretKey: pg_username
      remoteRef:
        key: vaultwarden/postgres
        property: username
    - secretKey: pg_password
      remoteRef:
        key: vaultwarden/postgres
        property: password
    - secretKey: yubico_client_id
      remoteRef:
        key: vaultwarden/yubico
        property: client_id
    - secretKey: yubico_secret_key
      remoteRef:
        key: vaultwarden/yubico
        property: secret_key
