apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/subcategory: observability

resources:
  - metrics-server.yaml
  - prometheus-operator.yaml
