apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: flux-system
stringData:
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:GGOg8y/iflleqJAdUNlIe44AlOg=,iv:GwDdnnc8G3ThVh7VQUbq5atbA5czc+P8rrrzHbkDoc0=,tag:5B/CTlNVtWnue9KivPa/yw==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:IVzH67nKmXCsX2zBBks=,iv:4psshFgGy2HdTgguKyK1jTq6405Yj3WnRd8N27l9ZAM=,tag:RIyM9cmjo6csGLr3huJw8A==,type:str]
sops:
    age:
        - recipient: age1usemhw8v2nnr5nuxddrc7gsy3525hhv0na4hk2ur7tjara5cp90s7cpeen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRzZZM1BlYVNpVzBpbkpx
            ZVA4S0JoME0rQ09Mdklrb0d2RmRXNVU4eEE0Cm9QTTB0aTFYRmNzdEJxc2psL3h2
            cExZUGM1TEhYNFgxemVwbUx4MEVBcVEKLS0tIFVZYjJ5a3NUWVJsUFBNNFQvUkNv
            bUVFWlloRmlSblF5ZTBHZ1NicDRQUGcK/43MW8vYleVNE8EzLse2dF1dnZvUPgyS
            QeNnp5T03Gv+tK7oMxxVjwaXodqpf1JqqhO1nFCs29dgIrD3hJzamQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T20:50:42Z"
    mac: ENC[AES256_GCM,data:hdJBo32g6K4qtN47bPGHnG23kljInv83LJB1uDMeKgTqws28WpnvR6x3TwnNYXaSdIsr30zszsMwSm8rurxH7casVjqs0vnfsAtOYp1FEgGWZxyIZYlBEACyd9b7tlpdbxrE3XMQwy4lYsp94m+rSY+/aIILod5u03EDOA/WzOc=,iv:FXbFpQLe6juBm78IDfFHQ43H4rnSmL8gFlbeA2KxJSc=,tag:0EPDzpIxpXdWvmrXDah7/g==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|secretboxencryptionsecret|bootstraptoken|secret|id)$
    version: 3.11.0
