apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/category: infrastructure

resources:
  - security
  - network
  - storage
  - observability
  - databases
  - repositories
