apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: cilium-helm-values
    namespace: cilium-system
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml

resources:
  - helm.yaml
