apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbird-operator-config
  namespace: netbird
spec:
  interval: 1h
  install:
    remediation:
      retries: 5
    disableWait: true
  upgrade:
    remediation:
      retries: 5
  chart:
    spec:
      chart: netbird-operator-config
      version: 0.x.x
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: netbird-operator
  values:
    router:
      enabled: true
      replicas: 2
    policies:
      default:
        name: Kubernetes Default Policy
        sourceGroups:
          - All
