apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pangolin

labels:
  - pairs:
      app.kubernetes.io/module: pangolin

resources:
  - namespace.yaml
  - secrets.yaml
  - pangolin.yaml
