apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pangolin-newt-1-credentials
  namespace: pangolin
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pangolin-newt-1-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PANGOLIN_ENDPOINT: "https://pangolin.${EXTERNAL_DOMAIN}"
        NEWT_ID: "{{ .id }}"
        NEWT_SECRET: "{{ .secret_key }}"
  dataFrom:
    - extract:
        key: pangolin/kubernetes-1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pangolin-newt-2-credentials
  namespace: pangolin
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pangolin-newt-2-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PANGOLIN_ENDPOINT: "https://pangolin.${EXTERNAL_DOMAIN}"
        NEWT_ID: "{{ .id }}"
        NEWT_SECRET: "{{ .secret_key }}"
  dataFrom:
    - extract:
        key: pangolin/kubernetes-2
