apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: joplin-password-generator
spec:
  length: 64
  symbols: 0
  allowRepeat: true
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: joplin-cluster
  namespace: joplin
spec:
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: joplin-password-generator
  template:
    data:
      username: joplin
      password: "{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: joplin/postgres
          property: password
    - match:
        secretKey: username
        remoteRef:
          remoteKey: joplin/postgres
          property: username
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: joplin-postgres
  namespace: joplin
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: joplin-cluster-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - extract:
        key: joplin/postgres
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: joplin-backup-s3-account
  namespace: joplin
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: joplin-backup-s3-account
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACCESS_KEY: "{{ .access_key }}"
        SECRET_KEY: "{{ .secret_key }}"
  dataFrom:
    - extract:
        key: joplin/s3
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: joplin-secret-env
  namespace: vault
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: joplin-secret-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_USER: "{{ .username }}"
        POSTGRES_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: joplin/postgres
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: joplin-saml-metadata
  namespace: vault
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: joplin-saml-metadata
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        joplin-idp.xml: "{{ .metadata }}"
  dataFrom:
    - extract:
        key: joplin/authentik
