apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: backup-store
  namespace: joplin
spec:
  configuration:
    destinationPath: s3://joplin
    endpointURL: https://truenas.${INTERNAL_DOMAIN}:30292
    s3Credentials:
      accessKeyId:
        name: joplin-backup-s3-account
        key: ACCESS_KEY
      secretAccessKey:
        name: joplin-backup-s3-account
        key: SECRET_KEY
    wal:
      compression: gzip
    data:
      compression: gzip
  retentionPolicy: "7d"
