apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-cluster
  namespace: immich
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17-0.4.3
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: local-path
    size: 10Gi

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 512Mi

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  managed:
    roles:
      - name: immich
        ensure: present
        login: true
        superuser: true
        passwordSecret:
          name: immich-cluster-credentials
        connectionLimit: -1
        inherit: true

  bootstrap:
    recovery:
      source: backup
      database: immich
      owner: immich
      secret:
        name: immich-cluster-credentials
    # initdb:
    #   database: immich
    #   owner: immich
    #   secret:
    #     name: immich-cluster-credentials
    #   postInitSQL:
    #     - CREATE EXTENSION IF NOT EXISTS "vchord" CASCADE;
    #     - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;
  externalClusters:
    - name: backup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: backup-store
          serverName: immich-cluster

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: backup-store

  monitoring:
    enablePodMonitor: true
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-cluster-backup
  namespace: immich
spec:
  cluster:
    name: immich-cluster
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
