apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: immich-password-generator
spec:
  length: 64
  symbols: 0
  allowRepeat: true
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: immich-cluster
  namespace: immich
spec:
  updatePolicy: IfNotExists
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: immich-password-generator
  template:
    data:
      username: immich
      password: "{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: immich/postgres
          property: password
    - match:
        secretKey: username
        remoteRef:
          remoteKey: immich/postgres
          property: username
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: immich-redis
  namespace: immich
spec:
  updatePolicy: IfNotExists
  refreshInterval: 2160h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: immich-password-generator
  template:
    data:
      password: "{{ .password }}"
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: immich/redis
          property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secret-env
  namespace: immich
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: immich-secret-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        REDIS_URL: |-
          {{- $redisPassword := .redis_password -}}
          {{- $sentinelPassword := .redis_password -}}
          {{- $config := printf `{"sentinels":[{"host":"immich-redis-sentinel-0.immich-redis-sentinel-headless","port":26379,"host":"immich-redis-sentinel-1.immich-redis-sentinel-headless","port":26379,"host":"immich-redis-sentinel-2.immich-redis-sentinel-headless","port":26379}],"name":"myMaster", "password": "%s","sentinelPassword":"%s"}` $redisPassword $sentinelPassword -}}
          ioredis://{{ $config | b64enc }}
        DB_USERNAME: "{{ .dbuser }}"
        DB_PASSWORD: "{{ .dbpass }}"
  data:
    - secretKey: redis_password
      remoteRef:
        key: immich/redis
        property: password
    - secretKey: dbuser
      remoteRef:
        key: immich/postgres
        property: username
    - secretKey: dbpass
      remoteRef:
        key: immich/postgres
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-redis
  namespace: immich
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: immich-redis-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: immich/redis
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-postgres
  namespace: immich
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: immich-cluster-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - extract:
        key: immich/postgres
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-backup-s3-account
  namespace: immich
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: immich-backup-s3-account
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACCESS_KEY: "{{ .access_key }}"
        SECRET_KEY: "{{ .secret_key }}"
  dataFrom:
    - extract:
        key: immich/s3
