apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-root
spec:
  ca:
    secretName: cluster-intermediate-ca
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        TOKEN: "{{ .token }}"
  dataFrom:
    - extract:
        key: letsencrypt
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: afonso.antunes@live.com.pt
    privateKeySecretRef:
      name: letsencrypt-dns-private-key
    solvers:
      - dns01:
          cloudflare:
            email: afonso.antunes@live.com.pt
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: TOKEN
        selector:
          dnsZones:
            - ${EXTERNAL_DOMAIN}
