apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/subcategory: security

resources:
  - cluster-intermediate-ca.enc.yaml
  - cluster-issuer.yaml
  - bundle
  - secret-store.yaml
