name: Flux Local

on:
  pull_request:
    branches:
      - main
    paths:
      - "kubernetes/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Flux Local Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@8454b02a32e48d775b9f563cb51fdcb1787b5b93 # v2.7.5

      - uses: allenporter/flux-local/action/test@d4ebcae7ae08c8c8b8b7c1f515cf86759f9ca950 # v8.1.0
        with:
          path: kubernetes/clusters/production
          enable-helm: true
          debug: true

  diff:
    name: Flux Local Diff
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    strategy:
      matrix:
        resources: ["helmrelease", "kustomization"]
      fail-fast: false
    steps:
      - name: Checkout Pull Request Branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@8454b02a32e48d775b9f563cb51fdcb1787b5b93 # v2.7.5

      - uses: allenporter/flux-local/action/diff@d4ebcae7ae08c8c8b8b7c1f515cf86759f9ca950 # v8.1.0
        id: diff
        with:
          live-branch: ${{ github.event.repository.default_branch }}
          path: kubernetes/clusters/production
          resource: ${{matrix.resources}}
          sources: flux-system
          debug: true

      - name: Generate Token
        if: ${{ steps.diff.outputs.diff != '' }}
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Add Comment
        if: ${{ steps.diff.outputs.diff != '' }}
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2
        with:
          repo-token: "${{ steps.app-token.outputs.token }}"
          message-id: "${{ github.event.pull_request.number }}/kubernetes/${{ matrix.resources }}"
          message-failure: Diff was not successful
          message: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
